The Series


In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([12,-4,7,9])
print(s)

x = pd.Series([1,2,3,4],index=['a','b','c','d'])
print(x)
print(x.values)
print(x.index)

0    12
1    -4
2     7
3     9
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64
[1 2 3 4]
Index(['a', 'b', 'c', 'd'], dtype='object')


Selecting the Internal Elements

In [3]:
print(s[2])
print("-------------")
print(x['b'])
print("-------------")
print(s[0:2])
print("-------------")
print(x[['b','c']]) # fancy indexing
print("-------------")
print(x['b':])

7
-------------
2
-------------
0    12
1    -4
dtype: int64
-------------
b    2
c    3
dtype: int64
-------------
b    2
c    3
d    4
dtype: int64


Assigning Values to the Elements

In [4]:
s[1] = 100
print(s)

x['c'] = 100
print(x)

0     12
1    100
2      7
3      9
dtype: int64
a      1
b      2
c    100
d      4
dtype: int64


Defining Series from NumPy Arrays and Other Series

In [5]:
arr = np.array([1,2,3,4])
pds = pd.Series(arr)
print(pds)

x2 = pd.Series(x)
print(x2)
pds[2] = -2
print(pds)

0    1
1    2
2    3
3    4
dtype: int32
a      1
b      2
c    100
d      4
dtype: int64
0    1
1    2
2   -2
3    4
dtype: int32


Filtering Values


In [6]:
print(s)
print(s[(s>8) & ( s<50)])
print(s[s>9])


0     12
1    100
2      7
3      9
dtype: int64
0    12
3     9
dtype: int64
0     12
1    100
dtype: int64


Operations and Mathematical Functions


In [7]:
print(s/2)

0     6.0
1    50.0
2     3.5
3     4.5
dtype: float64


Evaluating Values

In [9]:
serd = pd.Series([1,0,2,1,2,3],index=['white','white','blue','green','green','yellow'])
print(serd,"\n")
print(serd.unique(),"\n")
print(serd.value_counts(),"\n")
print(serd.isin([0,3]),"\n")
print(serd[serd.isin([0,3])],"\n")

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64 

[1 0 2 3] 

1    2
2    2
0    1
3    1
Name: count, dtype: int64 

white     False
white      True
blue      False
green     False
green     False
yellow     True
dtype: bool 

white     0
yellow    3
dtype: int64 



In [10]:
np.array([1,2,3,4])

array([1, 2, 3, 4])